server:
  port: 2200

spring:
  cloud:
    config:
      server:
        git:
          searchPaths: xs-blog
          username: xxxxssss12
          password:
          #uri: git@github.com:xxxxssss12/config-center.git
          uri: https://github.com/xxxxssss12/config-center.git
  application:
    name: xs-blog-config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

logging:
  level:
    root: debug